### PR TITLE
Improvements and bugfixes

### PR DESCRIPTION
**Pull request by DirkMahler**
- upgraded to jQA 1.3.0
- Added 'Git' label to 'Repository'
- Optimized concept 'git:CurrentBranch'

### CODE REVIEW

**Comment by kontext-e** [comment]
After upgrading to jqa 1.3.0 it does not build anymore on my machine:

2017-09-26 13:39:14.301 [main] INFO StoreFactory - Connecting to store at 'file:/C:/Users/jn/projects/jqassistant-plugins/jqassistant/store'
Exception in thread "main" java.lang.NoSuchFieldError: BOOLEAN
        at org.neo4j.shell.ShellSettings.<clinit>(ShellSettings.java:42)
        at sun.misc.Unsafe.ensureClassInitialized(Native Method)
        at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
        at java.lang.reflect.Field.get(Field.java:393)
        at org.neo4j.kernel.configuration.AnnotatedFieldHarvester.findStatic(AnnotatedFieldHarvester.java:47)
        at org.neo4j.kernel.configuration.AnnotationBasedConfigurationMigrator.<init>(AnnotationBasedConfigurationMigrator.java:39)
        at org.neo4j.kernel.configuration.Config.<init>(Config.java:106)
        at org.neo4j.kernel.configuration.Config.<init>(Config.java:96)
        at org.neo4j.kernel.impl.factory.PlatformModule.<init>(PlatformModule.java:127)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.createPlatform(GraphDatabaseFacadeFactory.java:232)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:146)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:130)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory.newDatabase(GraphDatabaseFactory.java:101)
        at org.neo4j.graphdb.factory.GraphDatabaseFactory.lambda$createDatabaseCreator$0(GraphDatabaseFactory.java:89)
        at org.neo4j.graphdb.factory.GraphDatabaseBuilder.newGraphDatabase(GraphDatabaseBuilder.java:183)
        at com.buschmais.xo.neo4j.embedded.api.FileDatastoreFactory.createGraphDatabaseService(FileDatastoreFactory.java:31)
        at com.buschmais.xo.neo4j.embedded.api.FileDatastoreFactory.createGraphDatabaseService(FileDatastoreFactory.java:16)
        at com.buschmais.xo.neo4j.embedded.api.EmbeddedNeo4jXOProvider.createDatastore(EmbeddedNeo4jXOProvider.java:24)
        at com.buschmais.xo.impl.XOManagerFactoryImpl.<init>(XOManagerFactoryImpl.java:48)
      m.buschmais.xo.impl.bootstrap.XOBootstrapServiceImpl.createXOManagerFactory(XOBootstrapServiceImpl.java:39)
        at com.buschmais.xo.api.bootstrap.XO.createXOManagerFactory(XO.java:43)
        at com.buschmais.jqassistant.core.store.impl.AbstractGraphStore.start(AbstractGraphStore.java:49)
        at com.buschmais.jqassistant.commandline.task.AbstractTask.run(AbstractTask.java:67)
        at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:253)
        at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:205)
        at com.buschmais.jqassistant.commandline.Main.run(Main.java:91)
        at com.buschmais.jqassistant.commandline.Main.main(Main.java:62)
:jqascan FAILED

Have to investigate if it is only a misconfiguration here or a more general problem. Does
./gradlew clean check jacoco jqa
work on your machine?

**Comment by DirkMahler** [comment]
Just saw that after upgrading to jQA 1.3 some dependencies need to be updated, will fix this. But trying to build current master of this repository (not the PR)  locally is failing with

`
Execution failed for task ':jqascan'.
> Could not resolve all dependencies for configuration ':jqaRuntime'.
   > Could not find de.kontext-e.jqassistant.plugin:jqassistant.plugin.checkstyle:1.3.0-SNAPSHOT.
`

Any hints?

**Comment by kontext-e** [comment]
First time of a new release SNAPSHOT, try ./gradlew install jqa

**Comment by DirkMahler** [comment]
Can reproduce it now: the problem is that obviously there's a difference between Maven and Gradle regarding management of dependencies and the jQA runtime classpath contains a mix of Neo4j v2 and v3 artifacts. I'd recommend to explicitly exclude "com.buschmais.jqassistant:neo4jserver.neo4jv2:1.3.0" from the "jqassistant-commandline" artifact and replace it by "com.buschmais.jqassistant:neo4jserver.neo4jv3:1.3.0". I'm a Maven guy and not familiar with Gradle (shame on me...): how can this be done?

**Comment by kontext-e** [comment]
Thanks for your contribution!

**Pull request merged**
